### ISSUE TITLE
CarrierWave::Backgrounder undefined method 'configure'

### ISSUE THREAD

**Issue by phil9690** [patricklindsay/integral#20]
When I try to run rake db:migrate when setting up the app I get the following error:
`NoMethodError: undefined method 'configure' for CarrierWave::Backgrounder:Module`

I have the latest master locally and have my test app pointed to that. I was able to get around the issue by setting carrierwave to `~> 0.5` and carrierwave_backgrounder to `~> 0.4`, but it looks like it breaks image uploads.

**Comment by patricklindsay** [comment]
Add this to your Gemfile & run bundle:

```
# Remove this when new gem version is released (< 0.4.2)
gem 'carrierwave_backgrounder', git: 'git://github.com/lardawge/carrierwave_backgrounder.git'
```

This should solve the issue. The currently released version of `carrierwave_backgrounder` is nearly 2 years old. Hopefully a new version will be released soon, until then we have to point to master (I should have added this note to CHANGELOG).
