### ISSUE TITLE
Create designs for Backend UI Refresh

### ISSUE THREAD

**Issue by patricklindsay** [patricklindsay/integral#23]
The backend needs a UI refresh. I think it's time to remove Materialize and fully embrace [Foundation](http://foundation.zurb.com/sites/docs/) (latest version 6.3.1)

Designs need to be created for [mobile, tablet and desktop](http://foundation.zurb.com/sites/docs/media-queries.html). The design should be clean and tidy - taking some elements from Material design.

Check out [Deliciousthemes 34 outstanding admin panels](https://deliciousthemes.com/34-outstanding-admin-panels-for-your-web-applications/) for inspiration.

## Required Designs
- Dashboard
- Generic Object
  - Index Page
  - Edit Page
  - Create Page
  - Show Page
- User Profile Page
- Settings Page
- Lists
  - Show/Edit Page
- Images
  - Index Page
  - Show Page
  - Edit Page

## Generic Object Index Page Functionality
- Link to create page
- Grid which contains rows of objects
- Actions to view, edit and remove each object
- Search input
- Basic filtering (i.e. for posts it would have filtering by post status (draft, published)
- Pagination
- Possible area showing object recent activity (i.e. for posts it would be Phil updated ‘Awesome Post’ 5 minutes ago etc) or link to view object activity

## Generic Object Show Page Functionality
- Link to edit page
- Recent object history with link to full page

Functionality listed above is just a guideline, make sure all functionality in the current design is kept (plus model activity which will soon be implemented)

**Comment by phil9690** [comment]
I have started working on this:

https://github.com/phil9690/integral/tree/backend_styling
