### ISSUE TITLE
Missing assets

### ISSUE THREAD

**Issue by phil9690** [patricklindsay/integral#44]
When I create a new Rails app using the v2 branch, I am not able to start the app due to the following assets missing:

app/assets/images/mobile-icons/startup.png
app/assets/images/mobile-icons/touch-icon.png
app/assets/images/previews/default.jpg

Once these have been added to my app everything works correctly.

**Comment by patricklindsay** [comment]
What version of Rails are you running?

**Comment by phil9690** [comment]
Rails 5.1 and Ruby 2.3.1

**Comment by patricklindsay** [comment]
Fixed!
